// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.spw.proto;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
