// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.spw.proto;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021hello_world.proto\022\005proto\"\037\n\014HelloReque" +
      "st\022\017\n\007request\030\001 \001(\t\"!\n\rHelloResponse\022\020\n\010" +
      "response\030\001 \001(\t2\257\002\n\014HelloService\0229\n\nHello" +
      "World\022\023.proto.HelloRequest\032\024.proto.Hello" +
      "Response\"\000\022G\n\026HelloWorldServerStream\022\023.p" +
      "roto.HelloRequest\032\024.proto.HelloResponse\"" +
      "\0000\001\022G\n\026HelloWorldClientStream\022\023.proto.He" +
      "lloRequest\032\024.proto.HelloResponse\"\000(\001\022R\n\037" +
      "HelloWorldClientAndServerStream\022\023.proto." +
      "HelloRequest\032\024.proto.HelloResponse\"\000(\0010\001" +
      "B%\n\rcom.spw.protoB\017HelloWorldProtoP\001\210\001\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          @Override
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_HelloRequest_descriptor,
        new String[] { "Request", });
    internal_static_proto_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_HelloResponse_descriptor,
        new String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
