// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.spw.proto;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
